0-module:1-task: Solved first task
js-tasks-ru/jsbasic-20220124_lider-yamal pull request #1
Opened 2022-01-24 17:16 UTC by MaxPekur

2022-01-24 17:16 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @koalex должен запустить тесты.

2022-01-25 05:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-25 05:08 UTC, koalex requested changes
Нужно решить задачу с факториалом

2022-02-01 17:48 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-02-01 17:49 UTC, koalex approved these changes

2022-02-01 17:49 UTC, merged